version: '3.8'
services:
  traefik:
    image: traefik:latest
    container_name: traefik
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./config/traefik/traefik.yml:/etc/traefik/traefik.yml
    ports:
      - "80:80"
      - "8080:8080"

  nginx:
    image: nginx:latest
    container_name: nginx
    volumes:
      - ./config/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./config/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./web:/usr/local/nginx/html
    labels:
      - traefik.http.routers.nginx.rule=PathPrefix(`/home`)
      - traefik.http.services.nginx.loadbalancer.server.port=80

  zookeeper:
    image: zookeeper:latest
    container_name: zookeeper
    ports:
      - "2181:2181"

  mysql:
    image: mysql/mysql-server:latest
    container_name: mysql
    ports:
      - "3306:3306"

  redis:
    build: ./config/redis
    image: jsy/redis:latest
    container_name: redis
    ports:
      - "6379:6379"

  kafka:
    image: bitnami/kafka:latest
    container_name: kafka
    environment:
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
    ports:
      - "9092:9092"

  logstash:
    image: logstash:8.1.1
    container_name: logstash
    volumes:
      - ./config/logstash/config/:/usr/share/logstash/config/
      - ./config/logstash/pipeline/:/usr/share/logstash/pipeline/

  elasticsearch:
    image: elasticsearch:8.1.1
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
    ports:
      - "9200:9200"
      - "9300:9300"

  kibana:
    image: kibana:8.1.1
    container_name: kibana
    environment:
      ELASTICSEARCH_HOSTS: '["http://elasticsearch:9200"]'
    ports:
      - "5601:5601"

  jsy-cloud-bff-demo:
    build: ./jsy-cloud-bff-demo
    image: jsy/jsy-cloud-bff-demo:latest
    container_name: jsy-cloud-bff-demo
    labels:
      - traefik.http.routers.jsy-cloud-bff-demo.rule=PathPrefix(`/bff-demo`)
      - traefik.http.services.jsy-cloud-bff-demo.loadbalancer.server.port=10001

  jsy-cloud-provider-demo:
    build: ./jsy-cloud-provider-demo
    image: jsy/jsy-cloud-provider-demo:latest
    container_name: jsy-cloud-provider-demo