server:
  port: 10001
#  port: 0
spring:
  application:
    name: jsy-cloud-bff-demo
dubbo:
  protocol:
    name: tri
    port: -1
  registry:
    address: registry.jsy.com:2181
    protocol: zookeeper